name: Add Reviewers

on:
  workflow_call:
    inputs:
      build_result:
        required: true
        type: string
      actor:
        required: true
        type: string

jobs:
  add_reviewers:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Read reviewers from DEPENDABOTREVIEWERS
        id: read-reviewers
        run: |
          reviewers=$(grep -v '^#' DEPENDABOTREVIEWERS | tr '\n' ',' | sed 's/,$//')
          echo "reviewers=$reviewers" >> $GITHUB_ENV
      - name: Print out reviewers
        run: |
          echo "Reviewers: ${{ env.reviewers }}"
      - name: Add reviewers and comment
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pull_number = context.payload.pull_request.number;

            await github.rest.pulls.requestReviewers({
              owner,
              repo,
              pull_number,
              reviewers: '${{ env.reviewers }}'.split(','),
            });
            
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pull_number,
              body: 'dependabot was not able to automerge this pull request. Humans, please help 🤖',
            });
