name: Add Reviewers

on:
  workflow_call:
    inputs:
      build_result:
        required: true
        type: string
      actor:
        required: true
        type: string

jobs:
  add_reviewers:
    if: ${{ inputs.actor == 'dependabot[bot]' && inputs.build_result == 'failure' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Read reviewers from DEPENDABOTREVIEWERS
        id: read-reviewers
        run: |
          owners="["
          while IFS= read -r name
          do
            reviewers="$reviewers'$name', "
          done < DEPENDABOTREVIEWERS
          reviewers="${reviewers%, }]"
          echo "reviewers=$reviewers" >> $GITHUB_ENV
      - name: Print out reviewers
        run: |
          echo "Reviewers: ${{ env.reviewers }}"
      - name: Add reviewers and comment
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pull_number = context.payload.pull_request.number;
            const reviewersString = process.env.reviewers;
            const reviewers = JSON.parse(reviewersString.replace(/'/g, '"'))
            
            await github.rest.pulls.requestReviewers({
              owner,
              repo,
              pull_number,
              reviewers,
            });
            
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pull_number,
              body: 'dependabot was not able to automerge this pull request. Humans, please help 🤖',
            });
