name: ci

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 23.x]

    steps:
      - name: Log CI context 1
        run: |
          echo "Actor: ${{ github.actor }}"
      - name: Check on of required labels are set
        uses: docker://agilepathway/pull-request-label-checker:v1.1.2
        with:
          one_of: testing,hi # Must have exactly-one of these labels
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install --ignore-scripts

      - name: Docker start
        run: |
          docker compose up -d --quiet-pull

      - name: Build TS
        run: |
          node --run build

      - name: Schema preparation
        run: |
          node --run copy:config
          node --run db:wait
          npm run db:apply-migrations

      - name: Run Tests
        run: |
          node --run test:ci

      - name: Run lint
        run: |
          node --run lint   

      - name: DB stop
        run: |
          docker compose down

      - name: Generate and validate OpenAPI schema
        run: |
          node --run spec:generate

  log_stuff:
    needs: build
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Log build result
        run: echo '${{ needs.build.result }}'
      - name: Log actor
        run: echo '${{ github.actor }}'

  automerge:
    needs: build
    if: ${{ always() && github.actor == 'dependabot[bot]' && needs.build.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  add_reviewers:
    needs: build
    if: ${{ always() && github.actor == 'dependabot[bot]' && needs.build.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Add Reviewers
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pull_number = context.payload.pull_request.number;
            
            await github.rest.pulls.addReviewers({
              owner,
              repo,
              pull_number,
              reviewers: ['dariacm'],
            });
            
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pull_number,
              body: 'dependabot was not able to automerge this pull request. Humans, please help 🤖',
            });
